// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiHTUSWhKPfrEtakhE9qSOqjJR_X0s7OI',
    appId: '1:977557701611:web:272db1e3df57374cd84fae',
    messagingSenderId: '977557701611',
    projectId: 'fantacy-cricket-team-builder',
    authDomain: 'fantacy-cricket-team-builder.firebaseapp.com',
    storageBucket: 'fantacy-cricket-team-builder.appspot.com',
    measurementId: 'G-VFQWEZ5Q9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmS7V61_HFr_pDuz-3OfCsD-psyZNZcY',
    appId: '1:977557701611:android:11790a0a120d2d80d84fae',
    messagingSenderId: '977557701611',
    projectId: 'fantacy-cricket-team-builder',
    storageBucket: 'fantacy-cricket-team-builder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLvKUImvOtrbJr9q4qa5vy8YrK6k6LjM',
    appId: '1:977557701611:ios:cbf1f0c29dab5ae0d84fae',
    messagingSenderId: '977557701611',
    projectId: 'fantacy-cricket-team-builder',
    storageBucket: 'fantacy-cricket-team-builder.appspot.com',
    iosBundleId: 'com.example.team.builder.teamBuilder',
  );
}
